package com.oring.oring_wm_ui_test.apkTest.constants

object LogName {

    const val DSQN = "DSQN"
    const val ActivityManager = "ActivityManager"
    const val AutomaticBrightnessControllerEx = "AutomaticBrightnessControllerEx"
    const val Zygote = "Zygote"
    const val Com = "com"
    const val Typeface = "Typeface"
    const val MultiDex = "MultiDex"
    const val FirebaseInitProvider = "FirebaseInitProvider"
    const val PhoneWindow = "PhoneWindow"
    const val ShowFilePath = "ShowFilePath"
    const val SQLiteOpenHelper = "SQLiteOpenHelper"
    const val TouchFilterInputStageHelper = "TouchFilterInputStageHelper"
    const val BezellessGripSuppressionFilter = "BezellessGripSuppressionFilter"
    const val BufferQueueConsumer = "BufferQueueConsumer"
    const val SurfaceFlinger = "SurfaceFlinger"
    const val GPUD = "GPUD"
    const val Surface = "Surface"
    const val BufferQueueProducer = "BufferQueueProducer"
    const val Gralloc3 = "Gralloc3"
    const val ion = "ion"
    const val MiniDump = "MiniDump"
    const val Timeline = "Timeline"
    const val ViewRootImpl = "ViewRootImpl"
    const val ActivityTaskManager = "ActivityTaskManager"
    const val ActivityThread = "ActivityThread"
    const val BluetoothAdapter = "BluetoothAdapter"
    const val BluetoothLeScanner = "BluetoothLeScanner"
    const val FastBle = "FastBle"
    const val BufferQueue = "BufferQueue"
    const val BluetoothGatt = "BluetoothGatt"
    const val CreateTest = "CreateTest"
    const val HEX = "HEX"
    const val DeviceName = "DeviceName"
    const val Password = "Password"
    const val CloudConfig = "CloudConfig"
    const val fc_Status = "fc_Status"
    const val CheckPW = "CheckPW"
    const val blePassword = "blePassword"
    const val SP_SW = "SP_SW"
    const val EEWW = "EEWW"
    const val Choreographer = "Choreographer"
    const val sw_ini = "sw_ini"
    const val UiThreadStatement = "UiThreadStatement"
    const val AI_value = "AI_value"
    const val AI_raw = "AI_raw"
    const val Dashboard = "Dashboard"
    const val ForcingPage = "ForcingPage"

    const val AiPage = "AiPage"
    const val DiPage = "DiPage"
    const val DoPage = "DoPage"
    const val RTDPage = "RTDPage"
    const val NetworkStatus = "NetworkStatus"

    const val DeviceInfo = "DeviceInfo"
    const val RTD_mode = "RTD_mode"
    const val finish = "finish"
    const val TouchFlickNoti = "TouchFlickNoti"
    const val DeviceInfoTest = "DeviceInfoTest"
    const val NB_RSSI = "NB_RSSI"
    const val NB_RSRQ = "NB_RSRQ"
    const val NB_RSRP = "NB_RSRP"
    const val NB_SINR = "NB_SINR"
    const val KeepALive = "KeepALive"
    const val TTTIII = "TTTIII"

    const val chatty = "chatty"
    const val DataBits = "DataBits"
    const val Gateway = "Gateway"
    const val Listenable = "Listenable"
    const val Req_Enable = "Req_Enable"
    const val BitShift = "BitShift"
    const val Bau = "Bau"
    const val SERIAL_DATA_BITS = "SERIAL_DATA_BITS"
    const val Cloud = "Cloud"
    const val CS_Info = "CS_Info"
    const val CloudSetting = "CloudSetting"
    const val CS_WR_Info = "CS_WR_Info"
    const val Address_Compare = "Address_Compare"
    const val refresh_step_1 = "refresh_step_1"
    const val swmodeHH = "swmodeHH"
    const val swmode = "swmode"
    const val dashboardIO = "I/O"
    const val NetworkStatusTest = "NetworkStatusTest"

    const val w = "@W@"
    const val wd = "@WD"
    const val write = "@Write"

    const val READ_MODE = "Read Mode"
    const val MCU_MODE = "MCU_MODE"


//    const val 通道 = "通道"

}