package com.oring.oring_wm_ui_test.apkTest.constants

object SubLogName {

    /**type1*/

    const val GATEWAY_READ_ENABLE_LOW = "READ ENABLE LOW"
    const val GATEWAY_READ_ENABLE_HIGH = "READ ENABLE HIGH"
    const val GATEWAY_WRITE_ENABLE_LOW = "WRITE ENABLE LOW"
    const val GATEWAY_WRITE_ENABLE_HIGH = "WRITE ENABLE HIGH"

    /**type2*/
    const val GATEWAY_READ_BAUD_RATE = "READ BAUD_RATE"
    const val GATEWAY_READ_DATA_BITS = "READ DATA_BITS"
    const val GATEWAY_READ_PARITY = "READ PARITY"
    const val GATEWAY_READ_STOP_BITS = "READ STOP_BITS"
    const val GATEWAY_READ_TIMEOUT = "READ TIMEOUT"
    const val GATEWAY_WRITE_BAUD_RATE = "WRITE BAUD_RATE"
    const val GATEWAY_WRITE_DATA_BITS = "WRITE DATA_BITS"
    const val GATEWAY_WRITE_PARITY = "WRITE PARITY"
    const val GATEWAY_WRITE_STOP_BITS = "WRITE STOP_BITS"
    const val GATEWAY_WRITE_TIMEOUT = "WRITE TIMEOUT"

    /**type3*/
    const val GATEWAY_READ_INTERVAL = "READ INTERVAL"
    const val GATEWAY_READ_DATA_FORMAT = "READ DATA_FORMAT"
    const val GATEWAY_READ_NET_ID = "READ NET_ID"
    const val GATEWAY_READ_IO_TYPE = "READ IO_TYPE"
    const val GATEWAY_READ_ADDRESS = "READ ADDRESS"
    const val GATEWAY_READ_DATA_NUM = "READ DATA_NUM"
    const val GATEWAY_WRITE_NET_ID = "WRITE NET_ID"
    const val GATEWAY_WRITE_IO_TYPE = "WRITE IO_TYPE"
    const val GATEWAY_WRITE_ADDRESS = "WRITE ADDRESS"
    const val GATEWAY_WRITE_DATA_NUM = "WRITE DATA_NUM"
    const val GATEWAY_WRITE_DATA_FORMAT = "WRITE DATA_FORMAT"
    const val GATEWAY_WRITE_STOP_INTERVAL = "WRITE INTERVAL"









}


